// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:47334353646:web:06bffed793643bdacd61ff',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '47334353646',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'flutterapp-44f85',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'flutterapp-44f85.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'flutterapp-44f85.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:47334353646:android:5fffcafa9fd2fc5bcd61ff',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '47334353646',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'flutterapp-44f85',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'flutterapp-44f85.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:47334353646:ios:404f56bdcdc69246cd61ff',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '47334353646',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'flutterapp-44f85',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'flutterapp-44f85.firebasestorage.app',
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'] ?? '47334353646-0c5h04r66pmntrue4pukscqgg6patv0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:47334353646:ios:404f56bdcdc69246cd61ff',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '47334353646',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'flutterapp-44f85',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'flutterapp-44f85.firebasestorage.app',
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'] ?? '47334353646-0c5h04r66pmntrue4pukscqgg6patv0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_WINDOWS_APP_ID'] ?? '1:47334353646:web:c6df48a8c01b80decd61ff',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '47334353646',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'flutterapp-44f85',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'flutterapp-44f85.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'flutterapp-44f85.firebasestorage.app',
  );
}
